- hosts: app
  vars:
      JETTY_VERSION: 9.3.8.v20160314
      JETTY_BASE_URL: http://download.eclipse.org/jetty/stable-9/dist/
      JETTY_TARGET: /opt/jetty
  tasks:
  - name: create jetty target
    file: path={{ JETTY_TARGET }} state=directory mode=0755
  #- name: download jetty
#    get_url: url={{ JETTY_BASE_URL }}jetty-distribution-{{ JETTY_VERSION }}.tar.gz dest={{ JETTY_TARGET }}
  - name: download and unzip jetty
    unarchive: src={{ JETTY_BASE_URL }}jetty-distribution-{{ JETTY_VERSION }}.tar.gz dest={{ JETTY_TARGET }} copy=no
  - name: create symlink for current jetty version
    file: path={{ JETTY_TARGET }}/current state=link src={{ JETTY_TARGET }}/jetty-distribution-{{ JETTY_VERSION }}
  - name: create jetty base
    file: path={{ JETTY_TARGET }}/base state=directory mode=0755
  - name: setup jetty base
    copy: src={{ JETTY_TARGET }}/current/demo-base/start.ini dest={{ JETTY_TARGET }}/base remote_src=true
